name: pipelinecomponentsambie001

on:
    push:
        branches: ["master"]

jobs:
    version:
        name: Versionnage Automatique
        runs-on: ubuntu-latest
        if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
        steps:
            - uses: actions/checkout@v2
            - uses: oleksiyrudenko/gha-git-credentials@v2-latest
              with:
                  token: ${{secrets.GH_PERSONAL_ACCESS_TOKEN}}
            - run: git config --global user.name '${{secrets.GH_PUBLIC_NAME}}'
            - run: git config --global user.email '${{secrets.GH_EMAIL}}'
            - run: npm version patch -m "[RELEASE] %s"
            - run: git push
            - run: git tag
            - run: git push --tags
    publish:
        name: Publication sur npmjs.org
        runs-on: ubuntu-latest
        if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16.x
                  registry-url: "https://registry.npmjs.org"
            - run: npm install
            - run: npm ci
            - run: npm run build-lib
            - uses: JS-DevTools/npm-publish@v1
              with:
                  token: ${{secrets.NPM_TOKEN}}
    ftpdeploy:
        name: Deploiement par FTP
        runs-on: ubuntu-latest
        if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
        steps:
            - name: Get latest code
              uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16.x
                  registry-url: "https://registry.npmjs.org"
            - run: npm install
            - run: npm ci
            - run: npm run build-storybook
            - name: Sync files
              uses: SamKirkland/FTP-Deploy-Action@4.3.2
              with:
                  local-dir: "storybook-static/"
                  server-dir: "public_html/storybook/"
                  server: ${{secrets.FTP_SERVER}}
                  username: ${{secrets.FTP_USER}}
                  password: ${{secrets.FTP_PASSWORD}}
